### PR TITLE
Custom Templates (Vendor Contacts , HelpDesk with workflow, Expense Template with Workflow)

### PR DESCRIPTION
**Pull request by srirams007**
… or vendor) and Helpdesk for the employees to create request and tickets are being managed by organization. These templates created on top of using the Partner pack and functionality similar to the templates available earlier in SharePoint 2010 (FAB 40). Please review this and let us know the feedback. Please find the attached screenshot.
[template.screen.shot.pdf](https://github.com/OfficeDev/PnP-Partner-Pack/files/77023/template.screen.shot.pdf)

### CODE REVIEW

**Comment by PaoloPia** [comment]
Hi,
Thanks for resubmitting this. We're doing some planning for a V.2 of the PnP Partner Pack and this submission will be helpful. I hope you don't mind if we keep on hold this PR for a while (probably a couple of months) until we will be ready to include it in the V.2, having the right place to host it. Thanks again for your commitment and contribution.

**Comment by srirams007** [comment]
Thanks Paolo. We are interested in contribution to v2.0 please let us know
how we can contribute to v2.0.

**Comment by PaoloPia** [comment]
Hi,
We are now ready to include your templates in the new PnP Templates Gallery that will be available soon. Could you please create these templates as .PNP files (with all the needed files included in the package, and with a preview PNG image) and share them with us? We will have a look a their implementation and we plan to include them in the first group of templates in the new gallery. Thanks.

**Comment by VesaJuvonen** [comment]
Like @PaoloPia mentioned, we have now released the PnP Templates Gallery for open submissions - see more details from here - https://dev.office.com/blogs/pnp-templates-gallery-open-source-provisioning-templates.

You can now submit pnp templates to the https://github.com/OfficeDev/PnP-Provisioning-Templates repository and we'd ask you to follow the contribution guidance available from here - https://github.com/OfficeDev/PnP-Provisioning-Templates/blob/master/Documentation/Publishing-Guidelines.md.

When template is merged in, it will get automatically visible in the PnP Template gallery at http://templates-gallery.sharepointpnp.com/.

I'll close up this PR for now, since this is not the right location for these, but we would highly appreciate contributions on the public gallery, if this is still something you'd be interested on sharing. Thx for your contribution towards PnP initiative for the benefit of the community.

**Pull request closed without merging**
